### ISSUE TITLE
`PostProvider` ?

### ISSUE THREAD

**Issue by ccreusat** [edificeio/blog#47]
# Context React

https://github.com/edificeio/blog/blob/develop-b2school/frontend/src/routes/post/index.tsx

Est-ce que le `PostProvider` est vraiment nécessaire ?

Vu les composant dans la vue, passer les infos en props drilling (parent vers enfants) et gérer les `canPublish`, .. soit dans un custom hook soit directement dans le composant paraissait suffisant

**Comment by jcbe-ode** [comment]
Il a été supprimé au cours d'un refactor pour feat/WB-2356
